# -*- coding: utf-8 -*-
"""108060094 week4-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOUC4WWJdif6NHoLXF7DxmEQcfdYfPKg
"""

print("Hello Worid")

"""嗨～～～

哈哈哈
"""